### ISSUE TITLE
Link LLVM

### ISSUE THREAD

**Issue by iluuu1994** [SlayterDev/DeafShark#1]
This looks interesting. 

Where can I get the LLVM sources and how do I have to link them?
Maybe that would be worth adding to the README

**Comment by SlayterDev** [comment]
Thanks for the interest! The project is still in very early stages (the most you could run is a "Hello, World!" Program). As per your question, you can find the llvm sources at [llvm.org](http://llvm.org). The Xcode project already links the necessary libraries for you.

**Comment by iluuu1994** [comment]
I got it working, thanks!
